//
//  HomeModels.swift
//  Pokedex
//
//  Created by Mario Chávez on 16/12/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum HomeModels
{
  // MARK: Use cases
    
    enum fetchPokemon {
        struct Request
        {
        }
        
        struct Response {
            var error: Error?
            var pokemons = [PokemonsDataModel.Pokemon]()
        }

        struct ViewModel
        {
            var error: Error?
            var errorMessage: String?
            
            var pokemon = [PokemonsDataModel.Pokemon]()
            var emptyMessage: String?
            var numOfPokemon: Int?
        }
    }
    
    enum searchPokemon {
        struct Request
        {
            var pokemon: String
            var type: Int
        }
        
        struct Response {
            var error: Error?
            var id: Int
            var name: String
            let sprites: PokemonSearchDataModel.Sprites
        }

        struct ViewModel
        {
            var id: Int
            var name: String
            let sprites: PokemonSearchDataModel.Sprites?
//            let type: PokemonSearchDataModel.types?
        }
    }
}
