//
//  HomeRouter.swift
//  Pokedex
//
//  Created by Mario Chávez on 16/12/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HomeRouter: NSObject {

}
