//
//  HomePresenter.swift
//  Pokedex
//
//  Created by Mario Chávez on 16/12/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresenterInterface {
    func presentPokemon(response: HomeModels.fetchPokemon.Response)
    func searchPresentPokemon(response: HomeModels.searchPokemon.Response)
    func detailPresentPokemon(response: HomeModels.searchPokemon.Response)
}

class HomePresenter: HomePresenterInterface {
    weak var viewController: HomeDisplayInterface?

    func presentPokemon(response: HomeModels.fetchPokemon.Response) {
        var viewModel = HomeModels.fetchPokemon.ViewModel()
        
        if let error = response.error {
            viewModel.error = error
            viewModel.errorMessage = "No se encontró ningún pokemón"
        }
        else {
            if response.pokemons.count > 0 {
                viewModel.pokemon = response.pokemons
            }
            else {
                viewModel.emptyMessage = "No hay pokemones disponibles"
            }
        }
        
        viewController?.displayPokemon(viewModel: viewModel)
    }
    
    func searchPresentPokemon(response: HomeModels.searchPokemon.Response) {
        let viewModel = HomeModels.searchPokemon.ViewModel(id: response.id, name: response.name, sprites: response.sprites)
        
        viewController?.displaySearchPokemon(viewModel: viewModel)
    }
    func detailPresentPokemon(response: HomeModels.searchPokemon.Response) {
        let viewModel = HomeModels.searchPokemon.ViewModel(id: response.id, name: response.name, sprites: response.sprites)
        
        viewController?.displaySearchPokemon(viewModel: viewModel)
    }
}
