//
//  HomeInteractor.swift
//  Pokedex
//
//  Created by Mario Chávez on 16/12/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeInteractorInterface {
    func fetchPokemons()
    func searchPokemon(request: HomeModels.searchPokemon.Request)
}

class HomeInteractor: HomeInteractorInterface {
    
    var presenter: HomePresenterInterface?
    var worker: HomeWorkerInterface = HomeWorker()

    func fetchPokemons() {

        worker.fetchPokemons() { [weak self]  result in
            guard let strongSelf = self else { return }

            var response = HomeModels.fetchPokemon.Response()
            switch result {
            case .success(let pokemons):
                print(pokemons)
                response.pokemons = pokemons.results
            case .failure(let error):
                print(error)
                response.error = error
            }
            strongSelf.presenter?.presentPokemon(response: response)
        }
    }
    
    func searchPokemon(request: HomeModels.searchPokemon.Request) {
        worker.searchPokemon(request: request) { result in
            switch result {
            case .success(let pokemon):
                print(pokemon)
                let response = HomeModels.searchPokemon.Response(id: pokemon.id, name: pokemon.name, sprites: pokemon.sprites)
                if request.type == 0 {
                    self.presenter?.searchPresentPokemon(response: response)
                }
                else {
                    self.presenter?.detailPresentPokemon(response: response)
                }
            case .failure(let error):
                print(error)
            
            }
        }
    }
    
}
