//
//  PokemonDetailInteractor.swift
//  Pokedex
//
//  Created by Mario Chávez on 22/12/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PokemonDetailBusinessLogic
{
  func doSomething(request: PokemonDetail.Something.Request)
}

protocol PokemonDetailDataStore
{
  //var name: String { get set }
}

class PokemonDetailInteractor: PokemonDetailBusinessLogic, PokemonDetailDataStore
{
  var presenter: PokemonDetailPresentationLogic?
  var worker: PokemonDetailWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: PokemonDetail.Something.Request)
  {
    worker = PokemonDetailWorker()
    worker?.doSomeWork()
    
    let response = PokemonDetail.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
